---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - swagger.infra.doodle.com
  resources:
  - SwaggerSpecifications
  - swaggerdefinitions
  - swaggerhubs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - swagger.infra.doodle.com
  resources:
  - SwaggerSpecifications/status
  - swaggerdefinitions/status
  - swaggerhubs/status
  verbs:
  - get
  - patch
  - update
