{{/* Generated by <make manifests> from config/rbac/role.yaml, do not edit. */}}
{{- define "swagger-hub-controller.rbacRules" -}}
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  - events.k8s.io
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - swagger.infra.doodle.com
  resources:
  - swaggerdefinitions
  - swaggerhubs
  - swaggerspecifications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - swagger.infra.doodle.com
  resources:
  - swaggerdefinitions/status
  - swaggerhubs/status
  - swaggerspecifications/status
  verbs:
  - get
  - patch
  - update
{{- end }}
